### ISSUE TITLE
Habby, Louis, Leland, and Matt's Wine Up wine selection app

### ISSUE THREAD

**Issue by lelandjordon** [ga-dc/wdi9-project3-gallery#5]
Link to Angular app repo: https://github.com/habbywhyte/wine_up
Link to Rails API repo:     https://github.com/habbywhyte/wine_up_api
Link to deployed app:      http://habbywhyte.github.io/wine_up/#/

Things you'd like specific feedback on:  The github.io deployment isn't displaying anything written with Angular without going to /#/ in the URL.  Is there a script that's not loading as it should?

**Comment by RobertAKARobin** [comment]
# Project 3 Evaluation

Inline code comments:
    - https://github.com/habbywhyte/wine_up/pull/18/files
    - https://github.com/habbywhyte/wine_up_api/pull/2/files

## Back-end Technology

**2: Performing**

> Includes 2 models

I love the clear wine knowledge you demonstrate in your seed data with how you associate wines with specific types of food.

## Front-end Technology

**2: Performing**

> Front-end makes appropriate use of Angular controllers and states with ui-router. Includes 1 custom directive

## Code Quality

**1: Progressing**

> Code lacks proper formatting, includes commented out, non-functional code, or otherwise contains major issues of quality (DRY, naming, etc)

You guys have indentation all over the place. From an employability standpoint this is a major area for improvement. At the very least, use Atom's auto-indent functionality and pay attention to what it does.

## Deployment and Functionality

**1: Progressing**

> Application contains minimal functionality, but deployment is non-functional, or application contains major errors when used

There are several major errors apparent when the page is first loaded -- for instance, the navigation bar not working. Please remove nonfunctional code before sending it out, or at least include comments saying that it's nonfunctional. Additionally, only the "Read" functionality of CRUD is present.

## Planning / Process / Submission

**1: Progressing**

> App is submitted, with basic evidence of planning. Documentation exists, but lacks common areas such as setup instructions, description of application functionality and link to deployed application.

I think this is the crux of the issues with the app. Students who feel uncomfortable with material tend to go into "flight" mode and forego planning, feeling like they just need to jump into the code right away or they'll run out of time. This invariably turns out poorly.

Employers generally prefer good planners with mediocre coce to good coders with mediocre planning. This is why project managers generally have higher salaries.

With your next project, I would recommend writing out the series of commits you think you should make: "Boilerplate HTML"; "Added script tags for Angular"; "Added basic routes for Angular"; "Added basic index controller"... and so on.
